# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift

  pod 'Alamofire', '~> 5.2'
  pod 'CryptoSwift'
  pod 'UIKit-Plus', '~> 2.1.2'
end
